Implement keystore DEFAULT.share
The `share` sec and cfg objects keyword documentation is:

	A list of namespaces that objects are allowed to decode this keystore keys.

	The `*` special value means `all`.

	By default a keystore only shares to its own namespace.

Example:

	$ om bug2 config show
	[DEFAULT]
	id = 51c47f79-b5c9-47c7-b64c-e55a1980e4e5

	[env]
	a1 = b1

	[volume#1]
	type = shm
	size = 1m
	user = 1001
	group = 1001
	install =
	  /etc/ mode 0750 user 1000 group 1000
	  /etc/ssl/ mode 0700 user 1000 group 1000
	  /etc/ from cfg haproxy namespace test key haproxy.cfg mode 0640 user 1000 group 1000
	  /etc/ssl/front.pem from sec d key fullpem mode 0640 user 1000 group 1001 required
	  /etc/ssl/front.chain from sec d key certificate_chain required
	  /etc/profile.d/ from sec d key etc/profile.d/*
	  /data

	$ bin/om bug2 start --local
	19:17:07.049 INF bug2: ▶ do start [bin/om bug2 start --local] (origin user, sid a682e49a-ee9e-4ba2-bc71-f33a2f5f7cc6)
	19:17:07.099 INF bug2: volume#1: volume vol/bug2-vol-1 is already up
	19:17:07.123 ERR bug2: volume#1: start: unauthorized install /srv/bug2-vol-1.root.vol.reliable-leopard/etc/ from test/cfg/haproxy key haproxy.cfg
	19:17:07.142 INF bug2: ■ done start [bin/om bug2 start --local] in 92.17414ms, instance status is now O
	Error: bug2: volume#1: start: unauthorized install /srv/bug2-vol-1.root.vol.reliable-leopard/etc/ from test/cfg/haproxy key haproxy.cfg

	$ bin/om bug2 instance status -r
	bug2                         up  non-optimal placement
	└ instances
	  └ dev2n1                   up  node-frozen idle started
	    └ resources
	      └ volume#1   ........  up  bug2-vol-1
					 warn: unauthorized install /srv/bug2-vol-1.root.vol.reliable-leopard/etc/ from test/cfg/haproxy key haproxy.cfg

	$ om test/cfg/haproxy set --kw share+=root
	test/cfg/haproxy: committed

	$ om bug2 instance status -r
	bug2                         up  non-optimal placement
	└ instances
	  └ dev2n1                   up  node-frozen idle started
	    └ resources
	      └ volume#1   ........  up  bug2-vol-1