Add a test to highlight a duration converter regression (not fixed yet)
cvaroqui@eggplant:~/dev/omg$ go test ./util/converters/...
--- FAIL: TestDurationConvert (0.00s)
    --- FAIL: TestDurationConvert/valid_duration_expression_returns_expected_values (0.00s)
        --- FAIL: TestDurationConvert/valid_duration_expression_returns_expected_values/1y (0.00s)
            converters_test.go:31:
                	Error Trace:	converters_test.go:31
                	Error:      	Received unexpected error:
                	            	time: unknown unit "y" in duration "1y"
                	Test:       	TestDurationConvert/valid_duration_expression_returns_expected_values/1y
        --- FAIL: TestDurationConvert/valid_duration_expression_returns_expected_values/1d (0.00s)
            converters_test.go:31:
                	Error Trace:	converters_test.go:31
                	Error:      	Received unexpected error:
                	            	time: unknown unit "d" in duration "1d"
                	Test:       	TestDurationConvert/valid_duration_expression_returns_expected_values/1d
        --- FAIL: TestDurationConvert/valid_duration_expression_returns_expected_values/1w (0.00s)
            converters_test.go:31:
                	Error Trace:	converters_test.go:31
                	Error:      	Received unexpected error:
                	            	time: unknown unit "w" in duration "1w"
                	Test:       	TestDurationConvert/valid_duration_expression_returns_expected_values/1w
FAIL
FAIL	opensvc.com/opensvc/util/converters	0.002s
FAIL