Ensure converter return casted pointer value
This patch fix configureResource failures on absent non required options pointers
   SetValue needs a casted value pointer to avoid
   error: "Specified value to set is of a different type"

Now always return casted values for Size, Umask, duration converters