[test] Fix test panic
    --- FAIL: TestStart (0.00s)
        --- FAIL: TestStart/does_not_execute_start_command_if_status_is_already_up (0.00s)
    panic: interface conversion: interface is nil, not resource.ObjectDriver [recovered]
        panic: interface conversion: interface is nil, not resource.ObjectDriver

    goroutine 11 [running]:
    testing.tRunner.func1.2({0xbd7bc0, 0xc000197860})
        /usr/local/go/src/testing/testing.go:1396 +0x24e
    testing.tRunner.func1()
        /usr/local/go/src/testing/testing.go:1399 +0x39f
    panic({0xbd7bc0, 0xc000197860})
        /usr/local/go/src/runtime/panic.go:884 +0x212
    opensvc.com/opensvc/core/resource.(*T).GetObjectDriver(...)
        ./omg/core/resource/resource.go:481
    opensvc.com/opensvc/drivers/resapp.(*T).isInstanceSufficientlyStarted(0xc00018a580, {0xdd7718?, 0xc0001977d0?})
        ./omg/drivers/resapp/unix.go:114 +0x96
    opensvc.com/opensvc/drivers/resapp.(*T).CommonStatus(0xc00018a580, {0xdd7718, 0xc0001977d0})
        ./omg/drivers/resapp/unix.go:166 +0x11e
    opensvc.com/opensvc/drivers/resappforking.(*T).Status(0xc0001d8180?, {0xdd7718?, 0xc0001977d0?})
        ./omg/drivers/resappforking/main.go:72 +0x5a
    opensvc.com/opensvc/drivers/resappforking.T.Start({{{{{...}, 0xc0001977a0, {...}, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...}, ...}}, ...)
        ./omg/drivers/resappforking/main.go:47 +0x3ca
    opensvc.com/opensvc/drivers/resappforking.TestStart.func2(0xc0001f29c0)
        ./omg/drivers/resappforking/main_test.go:74 +0x20e
    testing.tRunner(0xc0001f29c0, 0xc000012828)
        /usr/local/go/src/testing/testing.go:1446 +0x10b
    created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1493 +0x35f