[drivers/rescontainerocibase] Fix enter regression (unexpected context)
This fixes following instance enter failure:
    # om foo enter --rid container#xxx
    Error: foo:: container#xxx: context canceled