Make objectaction refuse to start multiple instances if failover
Context
-------

Objects                         dev2n1        dev2n2        dev2n3
 plop1      up^     no    1/1 | X^            X             O

Starting a single instance => OK
--------------------------------

root@dev2n1:~/dev/om3# ./om3  plop1 start --node dev2n2
OBJECT NODE   SID
plop1  dev2n2 fab2c431-9598-423c-a38c-5c039283e366

root@dev2n1:~/dev/om3# ssh dev2n2 journalctl SID=fab2c431-9598-423c-a38c-5c039283e366
Nov 21 18:45:21 dev2n2 om3[1518178]: instance: plop1: do [/root/om3 plop1 start --local] (origin daemon/api)
Nov 21 18:45:22 dev2n2 om3[1518178]: instance: plop1: announce starting state
Nov 21 18:45:22 dev2n2 om3[1518178]: plop1: fs#1: peer dev2n3: abort: conflict
Nov 21 18:45:22 dev2n2 om3[1518178]: instance: plop1: resource fs#1 denied start
Nov 21 18:45:22 dev2n2 om3[1518178]: instance: plop1: announce idle state
Nov 21 18:45:22 dev2n2 om3[1518178]: instance: plop1: done [/root/om3 plop1 start --local] in 289.628962ms
Nov 21 18:45:22 dev2n2 om3[1518178]: plop1: abort start

Starting many instances => NOK
------------------------------

root@dev2n1:~/dev/om3# ./om3  plop1 start --node dev2n*
Error: plop1: cowardly refusing to start multiple instances: topology is failover