Fix 'om object switch --wait --to' when switching to the same node
Ensure events are replayed from the cache when switching to the same node
by enabling the wait flag in GetEvents.

Bug example on repeated om foo switch --to abcd --wait:
   Error: wait expectation placed@ failed on object foo: can't find
           instance status for node abcd