Test plog.Logger pointer receiver nilness in all public funcs
Resources now store the logger as a pointer, so tests can trigger
plog.Logger calls with the resource log unallocated... causing
this kind of panics:

	--- FAIL: TestT_Info (0.34s)
	    --- FAIL: TestT_Info/from_zero_app (0.00s)
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	    panic: runtime error: invalid memory address or nil pointer dereference
	[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0xce9427]

	goroutine 29 [running]:
	testing.tRunner.func1.2({0x13c3ca0, 0x1d64290})
	    /opt/hostedtoolcache/go/1.24.13/x64/src/testing/testing.go:1734 +0x21c
	testing.tRunner.func1()
	    /opt/hostedtoolcache/go/1.24.13/x64/src/testing/testing.go:1737 +0x35e
	panic({0x13c3ca0?, 0x1d64290?})
	    /opt/hostedtoolcache/go/1.24.13/x64/src/runtime/panic.go:792 +0x132
	github.com/opensvc/om3/v3/util/plog.(*Logger).Msgf(...)
	    /home/runner/work/om3/om3/util/plog/main.go:120
	github.com/opensvc/om3/v3/util/plog.(*Logger).Levelf(0x0, 0xff, {0x152f927?, 0x15299c8?}, {0xc00019f430, 0x1, 0x1})
	    /home/runner/work/om3/om3/util/plog/main.go:144 +0x47
	github.com/opensvc/om3/v3/util/plog.(*Logger).Tracef(...)
	    /home/runner/work/om3/om3/util/plog/main.go:132
	github.com/opensvc/om3/v3/drivers/resapp.(*T).CmdArgs(0xc00019f8f0?, {0x169e288?, 0xc00024f880?}, {0x0?, 0x0?}, {0x15135ab?, 0x4?})
	    /home/runner/work/om3/om3/drivers/resapp/unix.go:292 +0x5ad

Test nilness to transparently ignore logging when the logger is
not allocated.