Fix a stack on malformed config update orders
For example:

	$ om foo set --kw fs#1type=flag

would panic on:

	panic: runtime error: invalid memory address or nil pointer dereference
	[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xc8b545]

	goroutine 1 [running]:
	github.com/cvaroqui/ini.(*Key).Value(...)
	    /root/go/pkg/mod/github.com/cvaroqui/ini@v1.66.7-0.20220627091046-b218d4fc5c30/key.go:110
	github.com/opensvc/om3/core/xconfig.(*T).set.func1({{{0xc003da00d0, 0x8}, {0x0, 0x0}}, 0x1, {0xc003da00d9, 0x4}, 0x0})
	    /root/dev/om3/core/xconfig/main.go:527 +0x65

Add a test, so that this bogus set would produce a clean:

	Error: invalid key in fs#1type=flag