resvol driver fixes and enhancements
With

	[volume#1]
	name = {name}-{nodename}
	nodes = {nodename}
	size = 100m

... the provision action produces:

	Objects matching **                     dev2n1        dev2n2        dev2n3
	 svc1               up^     ha    1/1 | O*            o*            o*
	 vol/svc1-dev2n1    up^           1/1 | O
	 vol/svc1-dev2n2    down          0/1 |               X
	 vol/svc1-dev2n3    down          0/1 |                             X

But with

	[volume#1]
	nodes = {nodename}
	size = 100m

... the provision action now raises:

	Error: volume#1: provision: svc1-vol-1 conflicts with a volume of the same name on dev2n2

instead of overwriting the config and make instances disappear.