Return an error if a resource selector is set but resolves to none
Do not log the action, save a instance status evaluation.

Example:

	$ om test/svc/svc1 restart --rid ip#12
	Error: test/svc/svc1: resource does not exist