Fix local om commands not working without cluster.conf
For example, we want encap nodes without a running om daemon
to accept running local CRM commands asked by the hypervisor.

Before this patch, we faced:

	c1:/# om encap1 instance start
	Error: encap1: cluster nodes cache is empty (unreadable cluster config or not a cluster node)
	c1:/# om encap1 instance stop
	Error: encap1: cluster nodes cache is empty (unreadable cluster config or not a cluster node)

Due to the nodes kw converter not falling back to [localhost]
when nodeselector.Expand() returns nodeselector.ErrClusterNodeCacheEmpty