Support set/unset command on remote objects
If --local and --node are not specified, the set/unset commands
use the POST /object/path/.../config/{un}set handler.

This handler do the operation inline if the object has a local
instance, or proxy the request to a peer having a local instance.

If --local is set, do the set action inline directly from the
core/command code. If the object does not have a local instance
an error is returned.

If --node is set, do the set action on the specified peer nodes,
using the POST /instance/path/.../action/set api handler.

Examples:

$ curl -k -s -u xxx:xxx -X POST -G --data-urlencode "kw=app#0.start=/bin/false"  "https://localhost:1215/object/path/test/svc/svc1/config/set" | jq
{
  "detail": "app#0.start",
  "status": 401,
  "title": "Not allowed keyword (root-only)"
}

=> rbac is verified by the local api, before proxying

$ ./om3 plop set --kw fs#2.type=flag --kw env=TST

=> valid set, relayed request

$ ./om3 plop set --kw orchestrate=noo
Error: plop: 500 SetKeys: abort config commit: validation errors

=> invalid set, relayed request

$ ./om3 plop set --kw orchestrate=noo --local
Error: plop exists but has no local instance

=> local set, but no local instance

$ ./om3 plop set --kw orchestrate=noo --node dev2n2
OBJECT NODE   SID
plop   dev2n2 412c86b2-9496-4366-91cd-4d0766fc1a00

=> invalid set, direct peer request