Don't test if a match has a local instance in objectselection
Let the objectselection callers decide if they want to do that.

For those ease the filtering via a new naming.Paths.Existing()
function.

For one, objectaction.DoLocal() needs to verify path existance.

With this patch, we have a proper behaviour and informative
errors in the following scenarios:

$ ./om3 plop start --local
Error: plop exists but has no local instance

$ ./om3 plop ls
OBJECT AVAIL OVERALL
plop   down  down

$ ./om3 plopu* start --local
Error: plopu*: no such object