[core/omcmd] Fix object create --wait error: context deadline exceeded
Enhance `WaitInstanceMonitor` by introducing a dedicated client that
allows overriding the default timeout with `t.Timeout`.
This ensures flexibility in handling specific timeout requirements.

This should fix following error:
    Error: wait instance monitor update failed on object foo: context deadline exceeded (Client.Timeout or context cancellation while reading body)