[test imon] Refactor check and verify goroutine counts
Test example:

    typeset -i count=400 total=0
    for i in {1..100}; do
        total=total+count
        printf "[%3d total %6d] " $i $total
        go test -p 1  --timeout 1h --count $count --failfast ./daemon/imon/...  || break
    done
    printf "[%3d total %6d] Failed \n" $i $total

Failure example:

    [  1 total      5] ok  	github.com/opensvc/om3/daemon/imon	1.428s
    ...
    --- FAIL: Test_Orchestrate_HA (0.14s)
        --- FAIL: Test_Orchestrate_HA/ha (0.14s)
            orchestrate_test.go:151: iteration 10 starting
            orchestrate_test.go:153: Setup with drain duration 40ms
            main.go:76: Starting daemon with osvc_root_path=/tmp/Test_Orchestrate_HAha3493424621/001
            main.go:31: install ../../testdata/cluster.conf to /tmp/Test_Orchestrate_HAha3493424621/001/etc/cluster.conf
            main.go:31: install ../../testdata/ca-cluster1.conf to /tmp/Test_Orchestrate_HAha3493424621/001/etc/namespaces/system/sec/ca-cluster1.conf
            main.go:31: install ../../testdata/cert-cluster1.conf to /tmp/Test_Orchestrate_HAha3493424621/001/etc/namespaces/system/sec/cert-cluster1.conf
            orchestrate_test.go:159: Set initial node monitor value
            orchestrate_test.go:326: watching InstanceMonitorUpdated and ConfigUpdated for path: ha, max duration 2s
            main.go:31: install ./testdata/ha.conf to /tmp/Test_Orchestrate_HAha3493424621/001/etc/ha.conf
            orchestrate_test.go:178: --- starting icfg for ha
            orchestrate_test.go:183: waiting for watcher result
            orchestrate_test.go:342: --- starting omon for ha
            orchestrate_test.go:254: --- crmAction  [ha status -r]
            orchestrate_test.go:285: --- crmAction  [ha status -r] SetInstanceStatus ha avail:down overall:down provisioned:true updated:2023-02-28 16:23:57.652736578 +0100 CET m=+0.873534645
            orchestrate_test.go:291: --- crmAction  [ha status -r] done
            orchestrate_test.go:350: ----  WATCH InstanceMonitorUpdated ha state: idle localExpect: none globalExpect: none isLeader: false isHaLeader: false
            orchestrate_test.go:359: Verify if expected is reached for fast return
            orchestrate_test.go:350: ----  WATCH InstanceMonitorUpdated ha state: idle localExpect: none globalExpect: none isLeader: true isHaLeader: true
            orchestrate_test.go:359: Verify if expected is reached for fast return
            orchestrate_test.go:350: ----  WATCH InstanceMonitorUpdated ha state: ready localExpect: none globalExpect: none isLeader: true isHaLeader: true
            orchestrate_test.go:359: Verify if expected is reached for fast return
            orchestrate_test.go:350: ----  WATCH InstanceMonitorUpdated ha state: starting localExpect: none globalExpect: none isLeader: true isHaLeader: true
            orchestrate_test.go:359: Verify if expected is reached for fast return
            orchestrate_test.go:254: --- crmAction start [ha start --local]
            orchestrate_test.go:285: --- crmAction start [ha start --local] SetInstanceStatus ha avail:up overall:up provisioned:true updated:2023-02-28 16:23:57.663011692 +0100 CET m=+0.883809760
            orchestrate_test.go:291: --- crmAction start [ha start --local] done
            orchestrate_test.go:350: ----  WATCH InstanceMonitorUpdated ha state: idle localExpect: none globalExpect: none isLeader: true isHaLeader: true
            orchestrate_test.go:359: Verify if expected is reached for fast return
            orchestrate_test.go:350: ----  WATCH InstanceMonitorUpdated ha state: ready localExpect: none globalExpect: none isLeader: true isHaLeader: true
            orchestrate_test.go:359: Verify if expected is reached for fast return
            orchestrate_test.go:350: ----  WATCH InstanceMonitorUpdated ha state: ready localExpect: none globalExpect: none isLeader: true isHaLeader: true
            orchestrate_test.go:359: Verify if expected is reached for fast return
            orchestrate_test.go:350: ----  WATCH InstanceMonitorUpdated ha state: starting localExpect: none globalExpect: none isLeader: true isHaLeader: true
            orchestrate_test.go:359: Verify if expected is reached for fast return
            orchestrate_test.go:254: --- crmAction start [ha start --local]
            orchestrate_test.go:285: --- crmAction start [ha start --local] SetInstanceStatus ha avail:up overall:up provisioned:true updated:2023-02-28 16:23:57.674075691 +0100 CET m=+0.894873689
            orchestrate_test.go:291: --- crmAction start [ha start --local] done
            orchestrate_test.go:350: ----  WATCH InstanceMonitorUpdated ha state: idle localExpect: none globalExpect: none isLeader: true isHaLeader: true
            orchestrate_test.go:359: Verify if expected is reached for fast return
            orchestrate_test.go:350: ----  WATCH InstanceMonitorUpdated ha state: idle localExpect: started globalExpect: none isLeader: true isHaLeader: true
            orchestrate_test.go:359: Verify if expected is reached for fast return
            orchestrate_test.go:187: crm calls: [[ha status -r] [ha start --local] [ha start --local]]
            orchestrate_test.go:189: verify state
            orchestrate_test.go:193: verify global expect
            orchestrate_test.go:197: verify local expect
            orchestrate_test.go:201: verify leader
            orchestrate_test.go:205: verify ha leader
            orchestrate_test.go:209: verify calls
            orchestrate_test.go:210:
                	Error Trace:	orchestrate_test.go:210
                	Error:      	Not equal:
                	            	expected: [][]string{[]string{"ha", "status", "-r"}, []string{"ha", "start", "--local"}}
                	            	actual  : [][]string{[]string{"ha", "status", "-r"}, []string{"ha", "start", "--local"}, []string{"ha", "start", "--local"}}

                	            	Diff:
                	            	--- Expected
                	            	+++ Actual
                	            	@@ -1,2 +1,2 @@
                	            	-([][]string) (len=2) {
                	            	+([][]string) (len=3) {
                	            	  ([]string) (len=3) {
                	            	@@ -10,2 +10,7 @@
                	            	   (string) (len=7) "--local"
                	            	+ },
                	            	+ ([]string) (len=3) {
                	            	+  (string) (len=2) "ha",
                	            	+  (string) (len=5) "start",
                	            	+  (string) (len=7) "--local"
                	            	  }
                	Test:       	Test_Orchestrate_HA/ha
                	Messages:   	expected calls [[ha status -r] [ha start --local]], found [[ha status -r] [ha start --local] [ha start --local]]
            orchestrate_test.go:214: setup cancel and wait for drain duration 40ms
            orchestrate_test.go:218: Verify goroutine counts
            orchestrate_test.go:220: iteration 10 goroutines: 5
            orchestrate_test.go:227: iteration 10 duration: 137.548291ms now: 2023-02-28 16:23:57.773502861 +0100 CET m=+0.994300881
    FAIL
    FAIL	github.com/opensvc/om3/daemon/imon	1.003s
    FAIL
    [  3 total     15] Failed